# Generated by Django 4.0.1 on 2022-04-21 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_order_options_user_balance_alter_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_client',
        ),
        migrations.AddField(
            model_name='order',
            name='name_seller',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
