# Generated by Django 3.2.8 on 2023-01-27 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_name_client_order_name_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_seller',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, max_length=10, verbose_name='Баланс'),
        ),
    ]
